// Copyright 2021-2024 Kirill Scherba <kirill@scherba.ru>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Webrtc log contains log definition used in Teonet webrts packages
package teowebrtc_log

import (
	"fmt"
	"io"
	"log"
	"os"
)

// Teolog
type teolog struct {
	logFlags int
	packages packagesMap
}
type packagesMap map[string]*packageData
type packageData struct {
	show   bool
	prefix string
	log    *log.Logger
}

// Teonet webrtc modules name
const (
	Package_main                    = "main"
	Package_teowebrtc_log           = "teowebrtc_log"
	Package_teowebrtc_server        = "teowebrtc_server"
	Package_teowebrtc_client        = "teowebrtc_client"
	Package_teowebrtc_signal        = "teowebrtc_signal"
	Package_teowebrtc_signal_client = "teowebrtc_signal_client"
)

var logt *log.Logger

// Initialize Teonet Logger and set default parameters
var teologPtr *teolog = func() (t *teolog) {
	t = &teolog{
		// Logger flags
		logFlags: log.LstdFlags | log.Lmicroseconds | log.Lmsgprefix,
		// Application packages
		packages: packagesMap{
			Package_main:                    &packageData{show: true, prefix: "[MAIN  ] "},
			Package_teowebrtc_log:           &packageData{show: true, prefix: "[TEOLOG] "},
			Package_teowebrtc_server:        &packageData{show: true, prefix: "[WEBRTC] "},
			Package_teowebrtc_client:        &packageData{show: true, prefix: "[WEBCLI] "},
			Package_teowebrtc_signal:        &packageData{show: true, prefix: "[SIGNAL] "},
			Package_teowebrtc_signal_client: &packageData{show: true, prefix: "[SIGCLI] "},
		},
	}
	for packageName, pac := range t.packages {
		pac.log, _ = t.getLog(packageName)
	}
	logt = t.packages[Package_teowebrtc_log].log
	logt.Println("teolog created")
	return
}()

// getLog returns teowebrtc logger depend of package name
//
// The method creates new logger and sets its parameters:
//   - Output: os.Stdout if the package is visible, io.Discard if the package is not visible
//   - Prefix: the prefix of the log messages
//   - Flags: the log flags
func (teolog *teolog) getLog(packageName string) (logt *log.Logger, err error) {

	pac, ok := teolog.packages[packageName]
	if !ok {
		err = fmt.Errorf("wrong package %s", packageName)
	}

	// Log output
	var out io.Writer = os.Stdout
	if !pac.show {
		out = io.Discard
	}

	// Create new loger
	logt = log.New(out, pac.prefix, teolog.logFlags)
	pac.log = logt

	return
}

// GetLog returns teowebrtc logger depend of package name
func GetLog(packageName string) (logger *log.Logger) {

	logt.Printf("get log %s", packageName)

	pac, ok := teologPtr.packages[packageName]
	if !ok {
		logt.Printf("error: wrong package %s", packageName)
		return
	}
	logger = pac.log

	return
}

// SetVisibility sets the visibility of package log
//
// SetVisibility sets the visibility of the log messages generated by the
// specified package. If the visibility is set to true, the log messages will
// be written to the standard output. If the visibility is set to false, the
// log messages will be discarded.
//
// The visibility is set to false by default.
//
// The visibility can be set for any package, but it is mainly used to control
// the visibility of the log messages generated by the main package and the
// child packages.
func SetVisibility(packageName string, show bool) (err error) {

	pac, ok := teologPtr.packages[packageName]
	if !ok {
		err = fmt.Errorf("wrong package %s", packageName)
		return
	}

	pac.show = show

	var out io.Writer = os.Stdout
	if !pac.show {
		out = io.Discard
	}

	pac.log.SetOutput(out)

	return
}

// SetMainPackagePrefix sets main package prefix
//
// The prefix is a string that will be used as a prefix for all log messages
// generated by the main package. The prefix should be no longer than 6
// characters.
//
// The prefix is of the form "[<prefix>] " and is used to make it easier to
// identify which package is generating the log messages.
func SetMainPackagePrefix(prefix string) {
	teologPtr.packages[Package_main].prefix = fmt.Sprintf("[%6s] ", prefix[:6])
}
